### ISSUE TITLE
"Got a bad hardware address length for an AF_PACKET 16 8"

### ISSUE THREAD

**Issue by mattlpage** [burakince/docker-dotnet-sonarscanner#1]
Hello thank you for this repo!  It could be very useful.

I get a failure to connect to SonarQube (running locally on Docker for Windows).

As I search, the error seems related to mono versioning?  Do you still use and maintain this repo?  I think it could save me a lot of time.

+ PROJECT_KEY=ConsoleApplication1
+ PROJECT_NAME=ConsoleApplication1
+ PROJECT_VERSION=1.0
+ SONAR_HOST=http://172.17.0.4:9191
+ SONAR_LOGIN_KEY=fc9773a5563b74a68bd8267ebfa9db3377ac136a
+ mono /opt/sonar-scanner-msbuild/SonarQube.Scanner.MSBuild.exe begin /d:sonar.host.url=http://172.17.0.4:9191 /d:sonar.login=fc9773a5563b74a68bd8267ebfa9db3377ac136a /k:ConsoleApplication1 /n:ConsoleApplication1 /v:1.0
SonarQube Scanner for MSBuild 4.0.2
Default properties file was found at /opt/sonar-scanner-msbuild/SonarQube.Analysis.xml
Loading analysis properties from /opt/sonar-scanner-msbuild/SonarQube.Analysis.xml
Pre-processing started.
Preparing working directories...
12:56:37.155  Updating build integration targets...
12:56:37.208  Fetching analysis configuration settings...
Got a bad hardware address length for an AF_PACKET 16 8
Got a bad hardware address length for an AF_PACKET 16 8
12:56:37.476  Failed to request and parse 'http://172.17.0.4:9191/api/server/version': Error: ConnectFailure (Connection refused)
12:56:37.479  Could not connect to the SonarQube server. Check that the URL is correct and that the server is available. URL: http://172.17.0.4:9191

**Comment by burakince** [comment]
Hi @mattlpage 

Can you send me your SonarQube Server version?

Thanks,
Burak

**Comment by mattlpage** [comment]
Thank you so much for your quick reply!

I was misconfigured,  The "-v $(pwd):/project \" with windows git-bash did not put me in the right directory.  With "-v /$(pwd):/project \", I am having much more success.

I apologize for distracting your valuable time!  This project may prove very useful in my CI-CD piplelines.

Appreciate your work!

**Comment by burakince** [comment]
You're welcome. I didn't do anything. :)
